name: gradle.yml
on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@83c124bfb09badf85ddfbf01158b5592c1a78c4a

      - name: Build All
        run: "./gradlew buildServerWinX64 buildServerLinuxX64 :paper:shadowJar :velocity:shadowJar"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-libs
          path: |            
            build/libs/**
            paper/build/libs/*-all.jar
            velocity/build/libs/*-all.jar
